// _countryMasterStyle.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e8f0fe',
    padding: 16,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0b316b',
    letterSpacing: 0.3,
  },
  totalCountText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2563eb',
  },

  inputGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.7)',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    justifyContent: 'space-between',
    shadowColor: '#60a5fa',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(209,213,219,0.6)',
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: '#0b316b',
    marginBottom: 10,
  },
  nameInput: {
    width: '65%',
    height: 50,
  },
  codeInput: {
    width: '30%',
    height: 50,
  },
  validWrapper: {
    width: '40%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#0b316b',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    height: 50,
  },
  validLabel: {
    fontSize: 16,
    color: 'white',
    fontWeight: '600',
  },
  addButton: {
    width: '50%',
    height: 50,
    backgroundColor: '#0b316b',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 26,
  },

  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    shadowColor: '#60a5fa',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  itemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  countryItemText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0b316b',
  },
  editIcon: {
    fontSize: 20,
  },
  backButton: {
    marginTop: 14,
    backgroundColor: '#0b316b',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.3)',
  },
  backButtonText: {
    fontWeight: '700',
    color: 'white',
    fontSize: 15,
  },
});
